### ISSUE TITLE
error reading .hex file

### ISSUE THREAD

**Issue by leveltgn** [cleanflight/blheli-multishot#2]
reading file 14.75 for XM20A. Blhelisuite version 16.0.14.7.0.2

![errorhexfilereaderror_160913_1](https://cloud.githubusercontent.com/assets/22107345/18478292/f9f6dda4-79d0-11e6-8ccd-d34f05a46af3.png)

**Comment by cmturn0** [comment]
Download the .zip from releases and it should resolve this.  The .hex files are apparently getting corrupted when downloading individually from the "hex" directory.
