### ISSUE TITLE
16.65 Dshot ESC Signal Identification Tone

### ISSUE THREAD

**Issue by tefloncoated** [cleanflight/blheli-multishot#7]
Blheli_S 16.65 Startup Tones documentation reflects that for Dshot it should be 1 long beep, however i am getting five regular length ones.   The arming tones are as expected - three for Dshot 600

**Comment by IronicBadger** [comment]
Can confirm this behaviour too.

**Comment by cturn** [comment]
correct, I was going to change dshot to a long tone instead of 5 beeps, and it was becoming too many beeps.  But apparently didn't ever make the change, I'll correct the documentation, thanks.
